
spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://adjoda-dev-db.c32oag8wocyb.eu-west-3.rds.amazonaws.com:5432/connect228
    username: lefort
    password: lefort123